### PR TITLE
KUZ-599: refactor plugin context

### PR DESCRIPTION
**Pull request by scottinet**
:warning: To be merged **after** #9 and https://github.com/kuzzleio/kuzzle-plugin-socketio/pull/8 :warning:

### CODE REVIEW

**Comment by scottinet** [comment]
Travis errors are caused by the plugin installation: the proxy is now looking for the socketio plugin v2.0.0, but it still hasn't been published on NPM.
This will be fixed by reruning Travis after merging https://github.com/kuzzleio/kuzzle-plugin-socketio/pull/8

**Comment by benoitvidis** [comment]
LGTM

**Comment by ballinette** [comment]
+1

**Comment by ballinette** [comment]
Plugin approved and merged, just missing a last vote to merge this one ;)

**Comment by xbill82** [comment]
Legit! Merging!

**Pull request merged**
