### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by scottinet**
:warning: 
Tests cannot be run on this PR until https://github.com/kuzzleio/kuzzle-plugin-socketio/pull/9 and https://github.com/kuzzleio/kuzzle-plugin-websocket/pull/1 are merged.
:warning: 

Working on performance issues lead me to several and rather small improvements:

* Add websocket protocol plugin to default installed plugins
* `Backend.sendRaw` now takes a callback instead of returning a promise. This was done because callers of this method use callbacks, as do `socket.send`. So `sendRaw` promisified `socket.send`, and this method's callers unpromisified the result. Using callback is more effective and use less code.
* Deactivated message compression by default between the proxy and kuzzle servers
* Now installs kuzzle-common-objects@1.0.2 instead of an old git branch
* Added `try...catch` instructions to all protocol plugin calls, to prevent proxy crashs whenever a plugin fails
* Fix: rejected requests due to a timeout weren't removed from the pending list

### CODE REVIEW

**Comment by ballinette** [comment]
+1

**Comment by dbengsch** [comment]
bluebird dependency could be removed from the package.js .
Outside of that, :+1:

**Comment by benoitvidis** [comment]
+1
Do not merge till the led is green.

**Comment by scottinet** [comment]
@dbengsch > promises are still used, I simply removed the one used in the middle of callback-using functions :-)

**Pull request merged**
