### PR TITLE
KUZ-584 : Coverage of 100%, yeah :)

### PR DESCRIPTION
**Pull request by dbengsch**
:100: :100: :100: :100: :100:

### CODE REVIEW

**Comment by ballinette** [comment]
+1

**Comment by benoitvidis** [comment]
+1

**Comment by xbill82** [comment]
In `kuzzleProxy.test.js` two tests have the same header `method initPlugins must initialize plugins when activated` and make assertions on two results of the same operation. I think they should be merged.

**Comment by xbill82** [comment]
+100

**Pull request merged**
